### ISSUE TITLE
Link to documentation in the README is broken

### ISSUE THREAD

**Issue by stichbury** [ably-labs/scalable-serverless-editable-chat-demo#9]
As per the title -- the link to documentation on this page https://github.com/ably-labs/scalable-serverless-editable-chat-demo/tree/main/chat-web-app/store doesn't resolve (for me)

**Comment by Srushtika** [comment]
I've just tried this link in Incognito mode and it seems to work fine. Can you provide me more details of how you are trying to access it so I can reproduce the scenario? @stichbury
